=== SUBBARAMIREDDY-K/xml_sample/employees.xsd
<schema targetNamespace="http://empinfo.com"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<element name="employees">
<complexType>
<sequence>
<element name="employee" minOccurs="0" maxOccurs="unbounded">
<complexType>
<sequence>
<element name="empName"  type="string"/>
  <element name="eDesignation"  type="string"/>
<element name="salary"  type="decimal"/>
<element name="doj"  type="date"/>
<element name="experience"  type="integer"/>
<element name="organization"  type="string"/>
<element name="address" type="string"/>
</sequence>
</complexType>
</element>
</sequence>
</complexType>
</element>
</schema>

=== SUBBARAMIREDDY-K/xml_sample/employees.xml
<employees xmlns="http://empinfo.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://empinfo.com employees.xsd">
<employee>
    <empName>SUBBARAMI REDDY . K</empName>
    <eDesignation>DATA SCIENTIST </eDesignation>
    <salary>75000</salary>
    <doj>2023-09-03</doj>
    <experience>3</experience>
    <organization>GOOGLE</organization>
    <address>HI-TECH city,near Kondapur,Hyderabad</address>
</employee>
<employee>
    <empName>VEERA BHADRA SWAMY . CH </empName>
    <eDesignation>SALES MANAGER</eDesignation>
    <salary>100000</salary>
    <doj>2023-06-22</doj>
    <experience>3</experience>
    <organization>APPLE</organization>
    <address>1 Apple park Way,cupertino,Califorina,USA</address>
</employee>
</employees>
